// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"

// code.cpp
cpp11::strings c_render(const cpp11::strings& input, const cpp11::strings& data_json);
extern "C" SEXP _rinja_c_render(SEXP input, SEXP data_json) {
  BEGIN_CPP11
    return cpp11::as_sexp(c_render(cpp11::as_cpp<cpp11::decay_t<const cpp11::strings&>>(input), cpp11::as_cpp<cpp11::decay_t<const cpp11::strings&>>(data_json)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _rinja_c_render(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_rinja_c_render", (DL_FUNC) &_rinja_c_render, 2},
    {NULL, NULL, 0}
};
}

extern "C" void R_init_rinja(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
