# Generated by cpp11: do not edit by hand

parse_ <- function(input, config) {
  .Call(`_jinjar_parse_`, input, config)
}

render_ <- function(input, data_json) {
  .Call(`_jinjar_render_`, input, data_json)
}
